fix(build): Fix build on mac os
On MacOs build fails with:
Undefined symbols for architecture arm64:
            "_LSCopyApplicationURLsForBundleIdentifier", referenced from:
                _setApplication in libmac_notification_sys-a73ca30ec927359c.rlib[5](54532c69c7c8f551-notify.o)
            "_OBJC_CLASS_$_NSImage", referenced from:
                 in libmac_notification_sys-a73ca30ec927359c.rlib[5](54532c69c7c8f551-notify.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

notify-rust crate uses mac-notification-sys crate
but it does require to link against Apple's
AppKit framework and CoreServices.

Fix this by creating build.rs that adds the libraries when building on MacOs.

Signed-off-by: Alexander Atanasov <alex@zazolabs.com>